frase = str(input('Digite uma frase: '))
print('O tipo primitivo dessa frase é', type(frase))
print('Só tem espaços?', frase.isspace())
print('É um número?', frase.isnumeric())
print('É alfabético?', frase.isalpha())
print('É alfanumérico?', frase.isalnum())
print('É maiúsculo?', frase.isupper())
print('É minúsculo?', frase.islower())
print('Está capitalizada?', frase.istitle())
